# Pipeline to deploy PAM workflow using Ansible
# Additional reference:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo aap_username: $(aap_username)
    echo aap_automationcontroller_uri: $(aap_automationcontroller_uri)
  displayName: 'Display script variables'

- script: |
    curl -s -k -u '$(aap_username):$(aap_admin_password)' -H 'Content-Type: application/json' -X POST $(aap_automationcontroller_uri)/api/v2/workflow_job_templates/53/launch/
  displayName: 'Execute templates to redeploy container to KIE server'
